# Generated by Django 5.0.1 on 2024-06-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subscription_expiry',
        ),
        migrations.AddField(
            model_name='staff',
            name='merchant_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='merchant_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subscription_status',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
