# Generated by Django 5.0.1 on 2024-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0003_alter_staff_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='recurring_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subscription_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
