# Generated by Django 5.0.1 on 2024-06-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0004_alter_staff_recurring_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subscription_status',
            field=models.CharField(default='Inactive', max_length=100),
        ),
    ]
