# Generated by Django 5.0.1 on 2024-06-04 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0006_rename_image_postarticle_file_upload_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content_languages',
        ),
        migrations.AddField(
            model_name='category',
            name='content_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_management.language'),
        ),
    ]
