# Generated by Django 5.0.1 on 2024-06-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0007_remove_category_content_languages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postarticle',
            old_name='file_upload_url',
            new_name='file_upload',
        ),
    ]
