# Generated by Django 5.0.1 on 2024-06-04 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0008_rename_file_upload_url_postarticle_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postarticle',
            name='meta_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='postarticle',
            name='news_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_management.language'),
        ),
    ]
