# Generated by Django 5.0.1 on 2024-06-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0009_alter_postarticle_meta_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='recurring_count',
            new_name='Id_card_charage_amount',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='merchant_subscription_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='merchant_user_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='work_dists',
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('recurring_count', models.IntegerField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_management.staff')),
            ],
        ),
    ]
